#                                  LAB TASKS

#  Task1:  Create a 1D array of integers from 1 to 20


   
1. Reshape it into a 4x5 2D array.
2. Replace all elements in the last column with zeros.
3. Finally, flatten the array back to 1D and print the result.







In [10]:
import numpy as np

array1 = np.arange(1, 21)
print(array1)
array2 = array1.reshape(4, 5)
array2[:, -1] = 0
print(array2)
array3 = array2.flatten()
print("array after modifications:", array3)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  0]
 [ 6  7  8  9  0]
 [11 12 13 14  0]
 [16 17 18 19  0]]
array after modifications: [ 1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18 19  0]


#  Task2: Generate a 2D array of random integers between 10 and 50 with a shape of 5x5

   
1. Calculate and print the mean, sum, minimum, and maximum values for 
each row and each column separately.


In [11]:

array0 = np.random.randint(10, 50, (5, 5))
print("5x5 array:\n", array0)

row_means = np.mean(array0, axis=1)
row_sums = np.sum(array0, axis=1)
row_mins = np.min(array0, axis=1)
row_maxs = np.max(array0, axis=1)

print("\nRow-wise :")
for i in range(5):
    print(f"Row {i + 1}: Mean={row_means[i]}, Sum={row_sums[i]}, Min={row_mins[i]}, Max={row_maxs[i]}")


col_means = np.mean(array0, axis=0)
col_sums = np.sum(array0, axis=0)
col_mins = np.min(array0, axis=0)
col_maxs = np.max(array0, axis=0)

print("\nColumn-wise :")
for i in range(5):
    print(f"Column {i + 1}: Mean={col_means[i]}, Sum={col_sums[i]}, Min={col_mins[i]}, Max={col_maxs[i]}")


5x5 array:
 [[48 33 49 10 32]
 [34 41 44 37 13]
 [35 33 42 31 40]
 [24 35 15 22 14]
 [28 10 44 43 30]]

Row-wise :
Row 1: Mean=34.4, Sum=172, Min=10, Max=49
Row 2: Mean=33.8, Sum=169, Min=13, Max=44
Row 3: Mean=36.2, Sum=181, Min=31, Max=42
Row 4: Mean=22.0, Sum=110, Min=14, Max=35
Row 5: Mean=31.0, Sum=155, Min=10, Max=44

Column-wise :
Column 1: Mean=33.8, Sum=169, Min=24, Max=48
Column 2: Mean=30.4, Sum=152, Min=10, Max=41
Column 3: Mean=38.8, Sum=194, Min=15, Max=49
Column 4: Mean=28.6, Sum=143, Min=10, Max=43
Column 5: Mean=25.8, Sum=129, Min=13, Max=40


#  Task3: Create an identity matrix of size 4x4
   
1. Add a constant (e.g., 5) to each element in the diagonal.
2. Then replace the last row with a row of ones.


In [12]:
matrix = np.eye(4)

print("Orignal",matrix)
np.fill_diagonal(matrix, matrix.diagonal() + 6)

matrix[-1, :] = 1

print("modify identity matrix:\n", matrix)


Orignal [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
modify identity matrix:
 [[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [1. 1. 1. 1.]]


#  Task4: Create an identity matrix of size 4x4
   
1. Count and display the number of occurrences of each unique value in the array
2. List the indices of elements greater than 10.
   



In [13]:


array = np.random.randint(0, 20, 15)
print("Generated 1D array:", array)


unique_values, counts = np.unique(array, return_counts=True)
occurrences = dict(zip(unique_values, counts))
print("\n unique value:", occurrences)


greater_than_10 = np.where(array > 10)[0]
print(" indices greater than 10:", greater_than_10)


Generated 1D array: [18 11  4  0 10  7  0  6  2  7 18 12 13  0  3]

 unique value: {0: 3, 2: 1, 3: 1, 4: 1, 6: 1, 7: 2, 10: 1, 11: 1, 12: 1, 13: 1, 18: 2}
 indices greater than 10: [ 0  1 10 11 12]


#  Task5: Create a 3x4 array filled with random floating-point numbers between 0 and 1
   
1. Round each element to two decimal places
2. Replace the elements in the second column with 0.5
   


In [14]:

arr = np.random.rand(3, 4)

arr = np.round(arr, 2)

arr[:, 1] = 0.5

print("Modifiy array:\n", arr)


Modifiy array:
 [[0.74 0.5  0.45 0.54]
 [0.18 0.5  0.44 0.76]
 [0.04 0.5  0.61 0.28]]
